services:
  chat-api:
    build: .
    container_name: chat_api
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
      API_KEY: your-api-key
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: chatdb
      MONGODB_URI: mongodb://root:root@mongo:27017/rag_storage?authSource=admin
      MONGODB_DB_NAME: rag_storage
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RATELIMIT_ENABLED: true
      RATE_LIMIT_MAX_REQUESTS_PER_SEC: 5
      RATE_LIMIT_SEC: 10
      RATE_LIMIT_TEMP_BLOCK_DURATION: 30
      RATE_LIMIT_ABUSE_THRESHOLD: 10
      SLACK_ENABLED: 'false'
      CF_ENABLED: 'false'
      GOOGLE_CLIENT_ID: 1042385486548-cbbarmkjt095oe1th1c3093rpnohk5s3.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
      GOOGLE_CALLBACK_URL: https://dev-rag.ravex.io/api/v1/auth/google/callback
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: rag_storage
    volumes:
      - mongodata:/data/db

  redis:
    image: redis:7
    container_name: chat_redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data

volumes:
  mongodata:
  redisdata:
